name: flutter_spinbox_example
description: SpinBox for Flutter example app.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_spinbox_fork:
    path: ../
  flutter:
    sdk: flutter
  intl: ^0.16.1
flutter:
  uses-material-design: true
